import type { Metadata } from "next";
import { Cormorant_Garamond, DM_Sans } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
// import CustomCursor from "@/components/CustomCursor";

const cormorant = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin"],
  display: "swap",
});

const dmSans = DM_Sans({
  variable: "--font-dm",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const themeCookie = cookieStore.get("SBS_preferred_theme");
  const initialIsDark = themeCookie?.value === "dark";

  return (
    <html lang="en" className={initialIsDark ? "dark" : ""}>
      <body
        className={`relative ${cormorant.variable} ${dmSans.variable} font-dm antialiased overflow-hidden`}
      >
        <ThemeProvider initialIsDark={initialIsDark}>
          {children}
          {/* <CustomCursor /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
