import type { Metadata } from "next";
import { Cormorant_Garamond, DM_Sans, Geist } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { cn } from "@/lib/utils";
import Preloader from "@/components/Preloader";
import QueryProvider from "@/components/QueryProvider";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});


// import CustomCursor from "@/components/CustomCursor";

const cormorant = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

const dmSans = DM_Sans({
  variable: "--font-dm",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const themeCookie = cookieStore.get("SBS_preferred_theme");
  const initialIsDark = themeCookie
    ? themeCookie.value === "dark"
    : true;

  return (
    <html lang="en" className={cn(initialIsDark ? "dark" : "", "font-sans", geist.variable)}>
      <body
        className={`relative ${cormorant.variable} ${dmSans.variable} font-dm antialiased`}
      >
        <ThemeProvider initialIsDark={initialIsDark}>
          <QueryProvider>
            {/* <Preloader /> */}
            <div id="page-content" className="invisibl mt-14">
              {children}
            </div>
            {/* <CustomCursor /> */}
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
